
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - api-network

networks:
  api-network:
